services:
  pullit-local-api:
    build: .
    container_name: pullit-local-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_URL=jdbc:mariadb://mariadb:3306/mydatabase?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - pullit-local-network

  pullit-local-worker:
    build: .
    container_name: pullit-local-worker
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=local,worker
      - SPRING_MAIN_WEB_APPLICATION_TYPE=NONE
      - DB_URL=jdbc:mariadb://mariadb:3306/mydatabase?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - pullit-local-network

  mariadb:
    image: 'mariadb:12.0.2'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - pullit-local-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9486:9090
    networks:
      - pullit-local-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 9485:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - pullit-local-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9487:9100"
    networks:
      - pullit-local-network

  redis:
    image: 'redis:8.0.4-alpine'
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - pullit-local-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: pullit-local-rabbitmq
    ports:
      - "127.0.0.1:5672:5672"  # AMQP port
      - "127.0.0.1:15672:15672" # Management UI port
    networks:
      - pullit-local-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  pullit-local-network:

volumes:
  grafana-storage:
