spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # QA 환경에서는 데이터를 보존하기 위함.
    show-sql: false

  # QA 환경에서는 DevTools 비활성화
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true  # QA에서는 예외 정보 확인 가능
    include-stacktrace: on_param # 요청 시에만 스택트레이스 표시
    include-message: always
  forward-headers-strategy: framework

info:
  app:
    name: Pullit QA
    description: Pullit 스터디 플랫폼 QA 테스트 환경

logging:
  level:
    root: info
    org.springframework.security: info
    kr.it.pullit: info
  # QA 로그 파일 설정
  # file:
  #   name: logs/pullit-qa.log

management:
  endpoints:
    web:
      # QA 환경에서는 액추에이터 엔드포인트 노출 최소화
      exposure:
        include: "health,info,metrics"
      base-path: "/actuator"
  endpoint:
    health:
      show-details: always
#    env:
#      show-values: ALWAYS
#    configprops:
#      show-values: ALWAYS

# Rate Limiting 설정 (Resilience4j) - QA 환경에만 적용
resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2500 # 기간 내 허용 요청 수
        limitRefreshPeriod: 1m # 기간 (1분)
        timeoutDuration: 0 # 대기 시간 없음 (즉시 실패)
        registerHealthIndicator: true

cors:
  allowed-origins:
    - "https://www.pull.it.kr"
    - "https://pull.it.kr"
    - "https://local.pull.it.kr:5173"

# 나머지 외부 연동 설정(S3, Google, Kakao 키 등)은 application.yml의 정의를 상속
