-- 이 파일은 Flyway가 데이터베이스 스키마의 버전을 관리하기 위한 기준선 역할을 합니다.
-- 프로젝트의 모든 테이블 생성 DDL(CREATE TABLE ...)과 초기 데이터(INSERT INTO ...)를 이 파일에 작성하거나,
-- 또는 이 파일을 비워두고 첫 실행 시에는 `jpa.hibernate.ddl-auto: update`가 테이블을 생성하게 할 수 있습니다.
--
-- 이 후 모든 스키마 변경(ALTER TABLE, CREATE INDEX 등)은 반드시
-- V2__, V3__ 와 같은 새로운 마이그레이션 파일을 통해서만 관리되어야 합니다.
