name: Deploy to EC2 (Compose)

on:
  workflow_run:
    workflows: ["Code check (linter, formatter)"]
    types:
      - completed
    branches:
      - develop

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    # GitHub Environments 사용을 위해 environment 설정
    # GitHub 저장소의 Settings > Environments 에서 'qa' 환경을 생성해야 합니다.
    environment: qa
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ecr: false

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.EC2_SSH_KEY }}' > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Create app directory on EC2
        run: ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "mkdir -p /home/ubuntu/app"

      - name: Upload docker-compose (QA)
        run: scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no docker-compose.qa.yml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/docker-compose.qa.yml

      - name: Deploy with Docker Compose (QA)
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "\
            export DOCKER_IMAGE='${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}' && \
            export DB_USERNAME='${{ secrets.DB_USERNAME }}' && \
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}' && \
            export DB_ROOT_PASSWORD='${{ secrets.DB_ROOT_PASSWORD }}' && \
            export KAKAO_REST_API_KEY='${{ secrets.KAKAO_REST_API_KEY }}' && \
            export KAKAO_CLIENT_SECRET='${{ secrets.KAKAO_CLIENT_SECRET }}' && \
            export S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' && \
            export S3_SECRET_KEY='${{ secrets.S3_SECRET_KEY }}' && \
            export GEMINI_API_KEY='${{ secrets.GEMINI_API_KEY }}' && \
            export SCHEME='${{ secrets.SCHEME }}' && \
            export BASE_URI='${{ secrets.BASE_URI }}' && \
            export ACCESS_CONTROL_ALLOWED_ORIGINS='${{ secrets.ACCESS_CONTROL_ALLOWED_ORIGINS }}' && \
            export AWS_REGION='ap-northeast-2' && \
            cd /home/ubuntu/app && \
            docker compose -f docker-compose.qa.yml down --remove-orphans && \
            docker compose -f docker-compose.qa.yml pull && \
            docker compose -f docker-compose.qa.yml up -d \
          "
      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/ec2_key.pem
