name: Code check (linter, formatter)

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  code_check:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2
      # DB 관련 변수는 빌드/테스트 시 내장 DB를 사용하므로 불필요

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "gradle"

      - name: Login to Docker registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ecr: false

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Check a code with Gradle
        run: ./gradlew codeCheck
      - name: Build
        run: ./gradlew build --no-daemon --continue

      - name: Build and push image with tags (latest and sha)
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          secrets: |
            ACCESS_CONTROL_ALLOWED_ORIGINS=${{ secrets.ACCESS_CONTROL_ALLOWED_ORIGINS }}
            AWS_REGION=ap-northeast-2
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}