name: PR Title Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        # 이 단계의 결과를 나중에 사용하기 위해 ID를 부여합니다.
        id: pr_title_lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            btsk-\d+

      - name: Add comment if title is invalid
        uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.pr_title_lint.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            PR 제목을 아래와 같이 작성해주세요.

            ```
            btsk-<이슈번호>: <제목>
            ```

            Details:

            ```
            ${{ steps.pr_title_lint.outputs.error_message }}
            ```

      - name: Delete comment if title is valid
        if: ${{ steps.pr_title_lint.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
